### ISSUE TITLE
Allow WebSocket subscription without specifying account filter

### ISSUE THREAD

**Issue by cenkalti** [Joohansson/NanoRPCProxy#14]
https://docs.nano.org/integration-guides/websockets/#subscribeunsubscribe

I would like to get confirmations for all accounts without specifying any account filter but that does not work currently.

**Comment by Joohansson** [comment]
This was a design choice because of traffic. If 1000 users subscribe to all accounts and there is a 100 BPS spam attack to ANY account. It would have to send 100,000 messages per second. I don't think I will implement that, if you don't have a counter-argument?

**Comment by cenkalti** [comment]
I thought the same. I built a payment gateway [Accept Nano](https://github.com/accept-nano/accept-nano) and was testing compatibility with NanoRPCProxy. Instead managing the account list locally, subscribing for all accounts and filtering on client side was much easier but that would increase the bandwidth consumption on both the gateway and the proxy.
