### ISSUE TITLE
WebSocket subscription does not return `id` field

### ISSUE THREAD

**Issue by cenkalti** [Joohansson/NanoRPCProxy#15]
https://docs.nano.org/integration-guides/websockets/#acknowledgement

If requests includes an `id`, it must be returned in acknowledgement message.

**Comment by Joohansson** [comment]
Ok, will fix

**Comment by cenkalti** [comment]
@Joohansson I can work on this and #16 if you want. Can I send you a PR?

**Comment by Joohansson** [comment]
> @Joohansson I can work on this and #16 if you want. Can I send you a PR?

Sure that would be great! I've been a bit busy lately. After the PR I just need to make sure it will work with Nault.cc as it's using this lib as the backend. Or if you want to check that yourself as part of it. You can specify your custom backend in the wallet. But that's just an extra check if you think it's fun.

**Comment by Joohansson** [comment]
@cenkalti Did you start doing any work on this? Because I don't want to start if you already have something close to a PR? If not, just let me know and I will start looking into this myself.

**Comment by cenkalti** [comment]
@Joohansson I am sorry I couldn't start working on this yet. I am moving my house and I am very busy at the moment. I don't think that I can work on this near future. Please go on if you have time.
