### ISSUE TITLE
Possible integration of p2PoW

### ISSUE THREAD

**Issue by Joohansson** [Joohansson/NanoRPCProxy#25]
Investigate and possible integration. Since this is not a wallet and workers needs to be paid I would assume this will be done in a relay kind of fashion. Maybe make the p2pow integration easier for other wallets or services.

Or maybe if a private key is provided and pow cost will be paid in full by the person who runs the proxy. Or both options.

Or if it should go via the token system. Purchase tokens which will be used to pay the pow.

https://github.com/anarkrypto/P2PoW

**Comment by anarkrypto** [comment]
excelent idea!
