### ISSUE TITLE
Expose representatives list from mynano.ninja

### ISSUE THREAD

**Issue by aspic** [Joohansson/NanoRPCProxy#40]
Makes it easier for wallets to implement representative change. This is something we could expose through the proxy, and also cache: https://mynano.ninja/api/accounts/verified. Also talk to person behind the site to get an OK.

**Comment by Joohansson** [comment]
The API is limited to 500 requests/h so the only thing to keep in mind is to have the cache set so this is not exceeded. But the rep list could probably be cached for 5min at least. That's just 12 req/h.

**Comment by BitDesert** [comment]
OK for me.
Only the node API is rate limited, the verified reps are not limited at all. But I would recommend implementing the cache nevertheless, otherwise you would relay every request and the list doesn't change that often.
