### ISSUE TITLE
Move to idiomatic javascript project structure

### ISSUE THREAD

**Issue by aspic** [Joohansson/NanoRPCProxy#74]
Suggest we move files to this structure:
```
├── src
│   ├── proxy.ts
│   └── ...files.ts
├── .dockerignore
├── .gitignore
├── .npmignore
├── Dockerfile
├── docker-compose.yml
├── package.json
└── REAME.md
```
Main reason for this is that it's a more idiomatic approach of structuring a Javascript project. Nice bonus is that we can stop running npm and docker with ---prefix/context.

**Comment by Joohansson** [comment]
Sure sounds good to me, as long as we update any references in the readme
